### ISSUE TITLE
Little help? Could not open library 'glib-2.0.0': dlopen(glib-2.0.0, 5): image not found.

### ISSUE THREAD

**Issue by bdhartz** [libvips/ruby-vips#284]
Hi team (John? Anyone?) Hoping for some help. I've spent hours on github/stackoverflow trying to triage this issue. Admittedly, I'm new to ruby and very new to getting development environments set up. I am on an M1 mac.

My VIPs-related unit tests fail with the following error:
LoadError: Could not open library 'glib-2.0.0': dlopen(glib-2.0.0, 5): image not found.
Could not open library 'libglib-2.0.0.dylib': dlopen(libglib-2.0.0.dylib, 5): image not found

Would really appreciate any help here. Also would be happy to jump on a zoom call and report findings back here!

Notes from my investigation/previous issues: 
(1) https://github.com/libvips/ruby-vips/issues/130 - libglib-2.0.dylib is on my system, in a few different places actually. Is the code looking for it somewhere else? 

$ locate libglib-2.0.dylib
/opt/homebrew/Cellar/glib/2.66.7/lib/libglib-2.0.dylib
/opt/homebrew/lib/libglib-2.0.dylib
/usr/local/lib/libglib-2.0.dylib
/usr/local/libglib-2.0.dylib

I see the suggestion that I should check: 
**you have glib and libvips in /usr/local/lib** - should they really be here if I'm primarily using brew, which puts things elsewhere? I've tried copying a bunch of files into /usr/local/lib, but I'm not sure exactly which files should be here for l
**you can run command-line vips stuff correctly** - irb > require 'vips' fails with the error mentioned above.
**your gem and Ruby know about /usr/local** - how can I check this? 

(2) vips --version output: 
vips-8.10.5-Fri Dec 18 10:14:09 UTC 2020

(3) I saw some other suggestions (I can't find them now) to modify lib/ffi/library.rb to use a direct path. However, 
    LIBC = '/usr/lib/libc.dylib' #original value
    #LIBC = '/System/DriverKit/usr/lib/system/libsystem_c.dylib' - tried this, didn't work
    #LIBC = '/opt/homebrew/Cellar/tcl-tk/8.6.11_1/lib/tcllibc/macosx-arm-clang/tcllibc.dylib' - tried this, didn't work

Interestingly, the output of  $ locate libc.dylib is below.
/opt/homebrew/Cellar/tcl-tk/8.6.11_1/lib/tcllibc/macosx-arm-clang/tcllibc.dylib

Looking for any guidance or suggestions. Thank you so much! Apologies if this is posted incorrectly, happy to remove it elsewhere. Thank you!

**Comment by jcupitt** [comment]
Hi @bdhartz, 

It used to "just work", but I've not tried ruby-vips on macos for a while, perhaps things have changed. I'll have a go later today.

**Comment by bdhartz** [comment]
> Hi @bdhartz,
> 
> It used to "just work", but I've not tried ruby-vips on macos for a while, perhaps things have changed. I'll have a go later today.

Thanks John, I look forward to hearing back! Let me know if you'd like to hop on a call or if I can provide any further info.

**Comment by jcupitt** [comment]
Oh, an M1 mac, I just noticed. I think brew is still a bit wobbly on the M1, you might need to wait a few months more before it'll work smoothly.

On this old imac I see:

```
21:45 $ brew install vips
==> Downloading https://homebrew.bintray.com/bottles/vips-8.10.5_2.catalina.bott
Already downloaded: /Users/john/Library/Caches/Homebrew/downloads/f57d2661c5701c4dfd7dc1bd9c4b9d068a75e845caa9ed5c1abedce79f8f33a7--vips-8.10.5_2.catalina.bottle.tar.gz
==> Pouring vips-8.10.5_2.catalina.bottle.tar.gz
Warning: vips dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/vips/8.10.5_2: 167 files, 13.9MB
✔ ~ 
21:46 $ ls -l /usr/local/lib/*vips*
lrwxr-xr-x  1 john  admin  48  8 Mar 21:46 /usr/local/lib/libvips-cpp.42.dylib -> ../Cellar/vips/8.10.5_2/lib/libvips-cpp.42.dylib
lrwxr-xr-x  1 john  admin  41  8 Mar 21:46 /usr/local/lib/libvips-cpp.a -> ../Cellar/vips/8.10.5_2/lib/libvips-cpp.a
lrwxr-xr-x  1 john  admin  45  8 Mar 21:46 /usr/local/lib/libvips-cpp.dylib -> ../Cellar/vips/8.10.5_2/lib/libvips-cpp.dylib
lrwxr-xr-x  1 john  admin  44  8 Mar 21:46 /usr/local/lib/libvips.42.dylib -> ../Cellar/vips/8.10.5_2/lib/libvips.42.dylib
lrwxr-xr-x  1 john  admin  37  8 Mar 21:46 /usr/local/lib/libvips.a -> ../Cellar/vips/8.10.5_2/lib/libvips.a
lrwxr-xr-x  1 john  admin  41  8 Mar 21:46 /usr/local/lib/libvips.dylib -> ../Cellar/vips/8.10.5_2/lib/libvips.dylib
✔ ~ 
21:49 $ gem install ruby-vips
Fetching ruby-vips-2.1.0.gem
Successfully installed ruby-vips-2.1.0
Parsing documentation for ruby-vips-2.1.0
Installing ri documentation for ruby-vips-2.1.0
Done installing documentation for ruby-vips after 0 seconds
1 gem installed
✔ ~ 
21:49 $ irb
irb(main):001:0' require 'vips'
=> true
irb(main):002:0> 
```

**Comment by jonfer** [comment]
I have the same problem, with an M1 as well. Let me know if you find a solution. Thank you

**Comment by jcupitt** [comment]
Sorry, I don't know what's wrong with your system. I did the most basic install and it all worked. Are you maybe attempting to use the Apple ruby? It blocks third party libraries for security. You must use the homebrew ruby.

On my mac (2012 imac), I see this:

```
10:49 $ which ruby
/usr/local/opt/ruby/bin/ruby
✔ ~ 
10:49 $ which vips
/usr/local/bin/vips
✔ ~ 
```

So I used `brew` to install vips and ruby and they are both in `/usr/local`.

```
10:50 $ ls /usr/local/lib/libglib*
/usr/local/lib/libglib-2.0.0.dylib /usr/local/lib/libglib-2.0.dylib
/usr/local/lib/libglib-2.0.a
✔ ~ 
10:50 $ ls /usr/local/lib/libvips*
/usr/local/lib/libvips-cpp.42.dylib /usr/local/lib/libvips.42.dylib
/usr/local/lib/libvips-cpp.a        /usr/local/lib/libvips.a
/usr/local/lib/libvips-cpp.dylib    /usr/local/lib/libvips.dylib
✔ ~ 
```

The relevant libraries are in there too.

```
10:50 $ vips --help
Usage:
  vips [OPTION…] [ACTION] [OPTIONS] [PARAMETERS] - VIPS driver program
...
```

I can run the vips command-line stuff.

```
10:50 $ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> 
```

And I can `gem install ruby-vips` and require it.

**Comment by bdhartz** [comment]
I think @jonfer is having an issue on a mac with M1/silicon architecture, similar to me above. I don't believe there was a solution for now.

**Comment by DotIN13** [comment]
Having the same problem using ruby-vips with Jekyll Picture Tag on an M1 Macbook.

**Comment by jcupitt** [comment]
Hi @DotIN13, you need to give a lot more information. What error did you get, how did you install everything, what versions are you running, where is your glib installed, which ruby are you using etc. etc. 

Could it perhaps be a native vs. x86 problem? For example, if glib has been built for x86 and ruby is native it obviously won't work.

**Comment by kleisauke** [comment]
I think PR https://github.com/ffi/ffi/pull/882 might fix this. As a workaround, you could try to symlink the whole `/opt/homebrew/lib` directory to `/opt/local/lib` (untested).

**Comment by DotIN13** [comment]
## Error

```log
Dependency Error: Yikes! It looks like you don't have jekyll_picture_tag or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll_picture_tag gem in your Gemfile as well. The full error message from Ruby is: 'Could not open library 'glib-2.0.0': dlopen(glib-2.0.0, 5): image not found. Could not open library 'libglib-2.0.0.dylib': dlopen(libglib-2.0.0.dylib, 5): image not found' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```

## How did I install everything?

brew: official install script, arm64

glib, vips: via brew, arm64

ruby: via rbenv, arm64

## Ruby Version

`ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]`

## glib

```shell
glib: stable 2.68.0 (bottled)
Core application library for C
https://developer.gnome.org/glib/
/opt/homebrew/Cellar/glib/2.68.0 (442 files, 22.0MB) *
```

## vips info

```shell
vips: stable 8.10.6 (bottled)
Image processing library
https://github.com/libvips/libvips
/opt/homebrew/Cellar/vips/8.10.6 (167 files, 14.2MB) *
```

So I guess it's all native but something just went wrong.

**Comment by DotIN13** [comment]
> I think PR [ffi/ffi#882](https://github.com/ffi/ffi/pull/882) might fix this. As a workaround, you could try to symlink the whole `/opt/homebrew/lib` directory to `/opt/local/lib` (untested).

After symlinking with the following command, it worked like butter, thanks a lot.

`sudo ln -s /opt/homebrew/lib /opt/local/lib`

**Comment by jcupitt** [comment]
Ah thanks for that Kleis, I hadn't realized homebrew had moved the lib area.

Related:  https://github.com/ioquatix/ffi-module

A more modern interface to ruby-ffi which has much better library searching. It might be useful to experiment with something similar.

**Comment by rdetert** [comment]
@DotIN13 @kleisauke Yes, this works. M1 strikes again!

**Comment by bdhartz** [comment]
@rdetert @DotIN13 @kleisauke - thanks for your work on this! For whatever reason, I don't have a /opt/local directory, so `sudo ln -s /opt/homebrew/lib /opt/local/lib` fails with `ln: /opt/local/lib: No such file or directory`. My `/opt/` only has homebrew in it, nothing else. Should I have a `/opt/local` and is there a way you know of that I can get this back to how it should be? Thanks a bunch!

**Comment by DotIN13** [comment]
@bdhartz You could try creating `/opt/local` with `mkdir -p /opt/local/lib`.

**Comment by greycampbell** [comment]
> > I think PR [ffi/ffi#882](https://github.com/ffi/ffi/pull/882) might fix this. As a workaround, you could try to symlink the whole `/opt/homebrew/lib` directory to `/opt/local/lib` (untested).
> 
> After symlinking with the following command, it worked like butter, thanks a lot.
> 
> `sudo ln -s /opt/homebrew/lib /opt/local/lib`

This was close for me, but I had to do `sudo ln -s /opt/homebrew/lib /usr/local/lib` to get it to work. I'd tried to install the older homebrew so this path already existed for me; you might have to manually create it

**Comment by mmhan** [comment]
I followed the instructions to create a symlink and I got the following error on my m1 machine.

```
❯ rails c
Running via Spring preloader in process 13791
Loading development environment (Rails 6.0.3.2)
2.6.5 :001 > require 'vips'
objc[13791]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[13791]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

I also get the same error if I used the ffi with ffi/ffi#882 fix implemented.

Is anyone else getting that?

**Comment by greycampbell** [comment]
> I followed the instructions to create a symlink and I got the following error on my m1 machine.
> 
> ```
> ❯ rails c
> Running via Spring preloader in process 13791
> Loading development environment (Rails 6.0.3.2)
> 2.6.5 :001 > require 'vips'
> objc[13791]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
> objc[13791]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
> ```
> 
> I also get the same error if I used the ffi with [ffi/ffi#882](https://github.com/ffi/ffi/pull/882) fix implemented.
> 
> Is anyone else getting that?

@mmhan I might be wrong but try adding "export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES" to your .bashrc or .zshrc

**Comment by Adverbly** [comment]
I ran into this as well. Also on M1. Had to modify the symlimk comments from above because I couldn't directly link the entire directory. What I used:
```
 sudo ln -s /opt/homebrew/lib/libglib-2.0.0.dylib /usr/local/lib/
 sudo ln -s /opt/homebrew/lib/libvips.42.dylib /usr/local/lib/
 sudo ln -s /opt/homebrew/lib/libgobject-2.0.0.dylib /usr/local/lib/
```

**Comment by leandrocastro** [comment]
I managed to solve it like this:

`sudo ln -s /opt/homebrew/lib /opt/local/lib`

Then I removed all installed gems:

`yes Y | gem uninstall -a -I`

Then I installed the bundle

`gem install bundler`

Then I installed all the gems again:

`bundle install`

**Comment by donncha** [comment]
```
$ bundle update ffi
```

might fix it. v1.15.0 doesn't look in `/opt/homebrew/lib`. v1.15.3+ does.

**Comment by galohernandez** [comment]
I did all the fixes but had no luck. Fixed using the command

brew install vips

Maybe this could help1

**Comment by stevecondylios** [comment]
@Adverbly's solution worked perfectly for me. I didn't quite understand what was going on, so I looked around a bit and learned: 

- Files in `/opt/...` are arm architecture, whereas files in `/usr/local/lib` are intel. 
- If ever unsure, you can find a dylib's architecture using the `file` command, [example](https://stackoverflow.com/a/3377166/5783745): 

```sh
file /opt/homebrew/lib/libglib-2.0.0.dylib
# /opt/homebrew/lib/libglib-2.0.0.dylib: Mach-O 64-bit dynamically linked shared library arm64
```
super handy!
- `ln -s` creates a symbolic link.
  - If the destination (second argument) already exists, it may not let you create the symbolic link, (which was the case for me). Since I already had libraries of the names of the symbolic links in `/usr/local/lib`, I moved them to the desktop; in hindsight, I could have simply deleted them, but I was being risk-averse. 

Hope it's useful.

**Comment by mattlindsey** [comment]
I just had this issue on a new M2 mac and solved it by removing the old x86 homebrew:
```
curl -fsSL -o /tmp/uninstall.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
arch -x86_64 /bin/bash /tmp/uninstall.sh --path=/usr/local
```

**Comment by jdsampayo** [comment]
There has been an ongoing discussion in multiple PRs about how to fix the Homebrew path issue. One notable PR that was merged, offering a more general solution, can be found at https://github.com/ffi/ffi/pull/968

While the fix has been merged, there hasn't been a new release yet. To address the `glib` problem, I used the master branch of `ffi` in my Bundler:

```ruby
gem 'ffi', git: 'https://github.com/ffi/ffi.git', branch: 'master'
```

If you prefer a more stable commit instead of the latest master, you can specify that. With this solution, there's no need to create symlinks between the arm64 and the Rosetta 2 (x86_64) versions of Homebrew.

**Comment by guschiavon** [comment]
> I did all the fixes but had no luck. Fixed using the command
> 
> brew install vips
> 
> Maybe this could help1

This has completely thrown my system configuration and now I'm not able to locally run any project that leverages the vips library...

**Comment by kleisauke** [comment]
> While the fix has been merged, there hasn't been a new release yet.

It appears that the Ruby-FFI gem has recently released [`v1.16.0`](https://github.com/ffi/ffi/releases/tag/v1.16.0), which should address this issue.

**Comment by guschiavon** [comment]
Someone help me please. I've had the `vips` library running smoothly with all my projects until running the `brew update vips` command on my shell. I currently get the following error when running `bundle exec jekyll s -l`:

```
bundle exec jekyll s -l
bundler: failed to load command: jekyll (/Users/gschiavon/.gem/ruby/2.7.3/bin/jekyll)
/Users/gschiavon/.gem/ruby/2.7.3/gems/ffi-1.16.1/lib/ffi/dynamic_library.rb:65:in `load_library': Could not open library 'vips.42': dlopen(vips.42, 0x0005): tried: 'vips.42' (no such file), '/System/Volumes/Preboot/Cryptexes/OSvips.42' (no such file), '/usr/lib/vips.42' (no such file, not in dyld cache), 'vips.42' (no such file), '/usr/local/lib/vips.42' (no such file), '/usr/lib/vips.42' (no such file, not in dyld cache). (LoadError)
Could not open library 'libvips.42.dylib': dlopen(libvips.42.dylib, 0x0005): Library not loaded: /opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib
  Referenced from: <555C8E69-E957-3A35-BB01-AF28A62E44B4> /opt/homebrew/Cellar/libmatio/1.5.23/lib/libmatio.11.dylib
  Reason: tried: '/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/usr/local/lib/libhdf5.200.dylib' (no such file), '/usr/lib/libhdf5.200.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/hdf5/1.14.2/lib/libhdf5.200.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/hdf5/1.14.2/lib/libhdf5.200.dylib' (no such file), '/opt/homebrew/Cellar/hdf5/1.14.2/lib/libhdf5.200.dylib' (no such file), '/usr/local/lib/libhdf5.200.dylib' (no such file), '/usr/lib/libhdf5.200.dylib' (no such file, not in dyld cache).
Could not open library '/usr/local/lib/libvips.42.dylib': dlopen(/usr/local/lib/libvips.42.dylib, 0x0005): Library not loaded: /opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib
  Referenced from: <555C8E69-E957-3A35-BB01-AF28A62E44B4> /opt/homebrew/Cellar/libmatio/1.5.23/lib/libmatio.11.dylib
  Reason: tried: '/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/usr/local/lib/libhdf5.200.dylib' (no such file), '/usr/lib/libhdf5.200.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/hdf5/1.14.2/lib/libhdf5.200.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/hdf5/1.14.2/lib/libhdf5.200.dylib' (no such file), '/opt/homebrew/Cellar/hdf5/1.14.2/lib/libhdf5.200.dylib' (no such file), '/usr/local/lib/libhdf5.200.dylib' (no such file), '/usr/lib/libhdf5.200.dylib' (no such file, not in dyld cache).
Could not open library '/opt/homebrew/lib/libvips.42.dylib': dlopen(/opt/homebrew/lib/libvips.42.dylib, 0x0005): Library not loaded: /opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib
  Referenced from: <555C8E69-E957-3A35-BB01-AF28A62E44B4> /opt/homebrew/Cellar/libmatio/1.5.23/lib/libmatio.11.dylib
  Reason: tried: '/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/opt/homebrew/opt/hdf5/lib/libhdf5.200.dylib' (no such file), '/usr/local/lib/libhdf5.200.dylib' (no such file), '/usr/lib/libhdf5.200.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/hdf5/1.14.2/lib/libhdf5.200.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/hdf5/1.14.2/lib/libhdf5.200.dylib' (no such file), '/opt/homebrew/Cellar/hdf5/1.14.2/lib/libhdf5.200.dylib' (no such file), '/usr/local/lib/libhdf5.200.dylib' (no such file), '/usr/lib/libhdf5.200.dylib' (no such file, not in dyld cache).
Searched in <system library path>, /usr/lib, /usr/local/lib, /opt/local/lib, /opt/homebrew/lib
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/ffi-1.16.1/lib/ffi/library.rb:95:in `block in ffi_lib'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/ffi-1.16.1/lib/ffi/library.rb:94:in `map'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/ffi-1.16.1/lib/ffi/library.rb:94:in `ffi_lib'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/ruby-vips-2.0.17/lib/vips.rb:528:in `<module:Vips>'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/ruby-vips-2.0.17/lib/vips.rb:525:in `<top (required)>'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/ruby-vips-2.0.17/lib/ruby-vips.rb:1:in `require'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/ruby-vips-2.0.17/lib/ruby-vips.rb:1:in `<top (required)>'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/jekyll_picture_tag-2.0.4/lib/jekyll_picture_tag/images/generated_image.rb:1:in `require'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/jekyll_picture_tag-2.0.4/lib/jekyll_picture_tag/images/generated_image.rb:1:in `<top (required)>'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/jekyll_picture_tag-2.0.4/lib/jekyll_picture_tag/images.rb:2:in `require_relative'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/jekyll_picture_tag-2.0.4/lib/jekyll_picture_tag/images.rb:2:in `<top (required)>'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/jekyll_picture_tag-2.0.4/lib/jekyll_picture_tag.rb:5:in `require_relative'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/jekyll_picture_tag-2.0.4/lib/jekyll_picture_tag.rb:5:in `<top (required)>'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/runtime.rb:60:in `require'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/runtime.rb:55:in `each'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/runtime.rb:55:in `block in require'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/runtime.rb:44:in `each'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/runtime.rb:44:in `require'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler.rb:176:in `require'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/jekyll-4.3.2/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/jekyll-4.3.2/exe/jekyll:11:in `<top (required)>'
        from /Users/gschiavon/.gem/ruby/2.7.3/bin/jekyll:25:in `load'
        from /Users/gschiavon/.gem/ruby/2.7.3/bin/jekyll:25:in `<top (required)>'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in `exec'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Users/gschiavon/.gem/ruby/2.7.3/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
        from /Users/gschiavon/.gem/ruby/3.0.0/bin/bundle:23:in `load'
        from /Users/gschiavon/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
```

To me, it looks like it's a missing file or misconfigured path to the library, am I correct assuming this?

I really need the library in order to leverage the `jekyll_picture_tag` plugin.

I can provide additional info as required.

**Comment by thomasbromehead** [comment]
> v1.16.0

Still having the issue with ffi 1.16.3 and Ventura 13.5 on an M1 Macbook Air

**Comment by jcupitt** [comment]
It was working fine on my M2 mac mini last time I tested it, I'll try again to verify.

**Comment by jcupitt** [comment]
I tried just now on my M2 mac mini, and it all worked. Here's what I did:

0. I use bash as my shell
1. I uninstalled all of homebrew to make sure I had a clean slate, I emptied my `.bash_profile`
2. Ran the usual `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` to install homebrew
3. I added homebrew to my path in the usual way.

Here's my `.bash_profile`:

```
export CLICOLOR=1

eval "$(/opt/homebrew/bin/brew shellenv)"
```

I also ran `eval "$(/opt/homebrew/bin/brew shellenv)"` directly to make sure everything was set up.

4. I ran `brew install vips`
5. I used the apple ruby (2.6.0) for testing, but I'm sure you should use the homebrew one. I ran `gem install ruby-vips --user-install` to install everything to `~/.gem`.

To verify it worked, I tried:

```
$ irb

WARNING: This version of ruby is included in macOS for compatibility with legacy software.
In future versions of macOS the ruby runtime will not be available by
default, and may require you to install an additional package.

irb(main):002:0> require "vips"
=> true
irb(main):003:0> Vips::Image.black(10,10)
=> #<Image 10x10 uchar, 1 bands, multiband>
irb(main):004:0> ^D
```

I have the various glib libraries in `/opt/homebrew`, and nothing in `/usr/local`:

```
$ ls /opt/homebrew/lib/libgob*
/opt/homebrew/lib/libgobject-2.0.0.dylib
/opt/homebrew/lib/libgobject-2.0.a
/opt/homebrew/lib/libgobject-2.0.dylib
$ ls /opt/homebrew/lib/libglib*
/opt/homebrew/lib/libglib-2.0.0.dylib /opt/homebrew/lib/libglib-2.0.dylib
/opt/homebrew/lib/libglib-2.0.a
$ ls /opt/homebrew/lib/libvip*
/opt/homebrew/lib/libvips-cpp.42.dylib /opt/homebrew/lib/libvips.42.dylib
/opt/homebrew/lib/libvips-cpp.dylib    /opt/homebrew/lib/libvips.dylib
$ ls /usr/local
$
```

**Comment by aristotekean** [comment]
> I tried just now on my M2 mac mini, and it all worked. Here's what I did:
> 
> 0. I use bash as my shell
> 1. I uninstalled all of homebrew to make sure I had a clean slate, I emptied my `.bash_profile`
> 2. Ran the usual `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` to install homebrew
> 3. I added homebrew to my path in the usual way.
> 
> Here's my `.bash_profile`:
> 
> ```
> export CLICOLOR=1
> 
> eval "$(/opt/homebrew/bin/brew shellenv)"
> ```
> 
> I also ran `eval "$(/opt/homebrew/bin/brew shellenv)"` directly to make sure everything was set up.
> 
> 4. I ran `brew install vips`
> 5. I used the apple ruby (2.6.0) for testing, but I'm sure you should use the homebrew one. I ran `gem install ruby-vips --user-install` to install everything to `~/.gem`.
> 
> To verify it worked, I tried:
> 
> ```
> $ irb
> 
> WARNING: This version of ruby is included in macOS for compatibility with legacy software.
> In future versions of macOS the ruby runtime will not be available by
> default, and may require you to install an additional package.
> 
> irb(main):002:0> require "vips"
> => true
> irb(main):003:0> Vips::Image.black(10,10)
> => #<Image 10x10 uchar, 1 bands, multiband>
> irb(main):004:0> ^D
> ```
> 
> I have the various glib libraries in `/opt/homebrew`, and nothing in `/usr/local`:
> 
> ```
> $ ls /opt/homebrew/lib/libgob*
> /opt/homebrew/lib/libgobject-2.0.0.dylib
> /opt/homebrew/lib/libgobject-2.0.a
> /opt/homebrew/lib/libgobject-2.0.dylib
> $ ls /opt/homebrew/lib/libglib*
> /opt/homebrew/lib/libglib-2.0.0.dylib /opt/homebrew/lib/libglib-2.0.dylib
> /opt/homebrew/lib/libglib-2.0.a
> $ ls /opt/homebrew/lib/libvip*
> /opt/homebrew/lib/libvips-cpp.42.dylib /opt/homebrew/lib/libvips.42.dylib
> /opt/homebrew/lib/libvips-cpp.dylib    /opt/homebrew/lib/libvips.dylib
> $ ls /usr/local
> $
> ```

It worked for me.
Macbook M1

**Comment by ansonhoyt** [comment]
`brew reinstall glib` fixed it on my M1, so maybe some folks can avoid a bigger reinstall.

### Details
My Homebrew packages have been installed to `/opt/homebrew` with `arm64` brew for many months, and vips was working, but I noticed the `.dylib`s folks mentioned were missing until I reinstalled glib:

```sh
# glib is installed but missing dylibs:
$ brew info glib
==> glib: stable 2.80.0 (bottled)
Core application library for C
https://developer.gnome.org/glib/
/opt/homebrew/Cellar/glib/2.80.0_2 (524 files, 36MB)
  Poured from bottle using the formulae.brew.sh API on 2024-03-31 at 19:30:11
...
$ ls /opt/homebrew/lib/libgob*
ls: /opt/homebrew/lib/libgob*: No such file or directory

# Reinstalled and now dylibs are found:
$ brew reinstall glib
$ ls /opt/homebrew/lib/libgob*
/opt/homebrew/lib/libgobject-2.0.0.dylib /opt/homebrew/lib/libgobject-2.0.dylib
/opt/homebrew/lib/libgobject-2.0.a

# Now vips loads without errors again:
$ ruby -e 'require "vips"'
```

(While I still have a few things installed with a separate `x86_64` homebrew install, neither glib nor vips were. That didn't seem to be an issue.)

**Comment by Yannmm** [comment]
> In my case, I'm using Mac OS 14.0 with M2, what I did is just to:
> 
> 1. brew install glib
> 2. brew install vips

worked for me. I'm using rails 7.1.3 on mac M1 chip.
